### ISSUE TITLE
Release latest version (0.1.2) to Maven Central

### ISSUE THREAD

**Issue by ChrisSSocha** [mnogu/gatling-kafka#12]
The current version on Maven Central is [0.1.0](https://mvnrepository.com/artifact/com.github.mnogu/gatling-kafka_2.11)

This version does not work with Gatling 2.2.4, but the latest version of the code (0.1.2) appears to work fine. Could you please update the package on Maven Central?

**Comment by neoscaler** [comment]
Can only second this. It is hard to use it in a Maven project currently.

**Comment by mnogu** [comment]
I've uploaded the current latest version 0.3.0 instead of 0.1.2.
https://repo1.maven.org/maven2/com/github/mnogu/gatling-kafka_2.12/0.3.0/
