### ISSUE TITLE
Publish to maven repo and Github releases?

### ISSUE THREAD

**Issue by daluu** [mnogu/gatling-kafka#3]
Hi, I see you tag formal releases of this project's code. It would be nice if you:
- compile the project's code with default config with the releases so it goes into Github release section of this project for one to download without compiling themselves if they use the defaults of the project.
- compile the project's code with default config to maven repo so that those that use Gatling with maven can pull it into their projects without the manual copy steps (or having to use their own custom maven config or local repo to host the compiled version of gatling-kafka). Or do you already do this? I didn't find it searching the public maven repo.

**Comment by mnogu** [comment]
Sorry for the late reply.

I uploaded gatling-kafka-assembly-0.0.6.jar and gatling-kafka-assembly-0.1.0.jar:
https://github.com/mnogu/gatling-kafka/releases

and artifacts to the Central Repository:
http://search.maven.org/#artifactdetails|com.github.mnogu|gatling-kafka_2.11|0.1.0|jar
